apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  annotations:
    deployment.kubernetes.io/change-cause: "Upgraded to version 2.0"
  labels:
    app: app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: app2
        image: macharavikishore/app2:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: app2
spec:
  selector:
    app: app2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app2
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    ingressClassName: alb
    alb.ingress.kubernetes.io/group.name: cloudcamp
spec:
  rules:
  - host: app2.practiceaws.site
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: app2
            port:
              number: 80
